# Generated by Django 3.0 on 2019-12-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0003_post_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
